package servidor;


/**
* servidor/monitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* martes 4 de diciembre de 2012 06:35:03 PM VET
*/

public interface monitor extends monitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface monitor
