package servidor;


/**
* servidor/monitorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* martes 4 de diciembre de 2012 06:35:03 PM VET
*/

abstract public class monitorHelper
{
  private static String  _id = "IDL:servidor/monitor:1.0";

  public static void insert (org.omg.CORBA.Any a, servidor.monitor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidor.monitor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (servidor.monitorHelper.id (), "monitor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidor.monitor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_monitorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidor.monitor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static servidor.monitor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servidor.monitor)
      return (servidor.monitor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servidor._monitorStub stub = new servidor._monitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static servidor.monitor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servidor.monitor)
      return (servidor.monitor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servidor._monitorStub stub = new servidor._monitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
