package servidor;


/**
* servidor/monitorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* martes 4 de diciembre de 2012 06:35:03 PM VET
*/

public abstract class monitorPOA extends org.omg.PortableServer.Servant
 implements servidor.monitorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("agregar", new java.lang.Integer (0));
    _methods.put ("borrar", new java.lang.Integer (1));
    _methods.put ("mostrar", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidor/monitor/agregar
       {
         String valor = in.read_string ();
         String $result = null;
         $result = this.agregar (valor);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // servidor/monitor/borrar
       {
         String valor = in.read_string ();
         String $result = null;
         $result = this.borrar (valor);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // servidor/monitor/mostrar
       {
         String $result = null;
         $result = this.mostrar ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidor/monitor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public monitor _this() 
  {
    return monitorHelper.narrow(
    super._this_object());
  }

  public monitor _this(org.omg.CORBA.ORB orb) 
  {
    return monitorHelper.narrow(
    super._this_object(orb));
  }


} // class monitorPOA
