package servidor;


/**
* servidor/monitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* martes 4 de diciembre de 2012 06:35:03 PM VET
*/

public interface monitorOperations 
{
  String agregar (String valor);
  String borrar (String valor);
  String mostrar ();
} // interface monitorOperations
