package servidor;

/**
* servidor/monitorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monitor.idl
* martes 4 de diciembre de 2012 06:35:03 PM VET
*/

public final class monitorHolder implements org.omg.CORBA.portable.Streamable
{
  public servidor.monitor value = null;

  public monitorHolder ()
  {
  }

  public monitorHolder (servidor.monitor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidor.monitorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidor.monitorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidor.monitorHelper.type ();
  }

}
